apm-server:
  host: "0.0.0.0:8200"
  secret_token: "${APM_SECRET_TOKEN}"
  rum:
    enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

setup.template.enabled: true
setup.dashboards.enabled: true

logging.level: info
logging.to_stderr: true
logging.to_files: false
